import { StyleSheet } from "react-native";
import { colors } from "@/src/theme/colors";

export const BG = colors.background;
export const CARD = colors.card;
export const BORDER = colors.border;
export const TEXT = colors.text;
export const MUTED = colors.muted;
export const GREEN = colors.primary;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: BG },

  header: {
    position: "absolute",
    left: 16,
    right: 16,
    zIndex: 50,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  headerTitle: {
    color: MUTED,
    fontSize: 11,
    letterSpacing: 1,
    fontWeight: "800",
  },
  iconBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(0,0,0,0.25)",
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
  },
  iconText: { color: TEXT, fontSize: 16, fontWeight: "900" },

  content: { paddingTop: 54, paddingHorizontal: 18, gap: 14 },

  heroWrap: {
    borderRadius: 26,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: BORDER,
  },
  hero: { height: 210, width: "100%" },
  heroImg: { borderRadius: 26 },
  heroOverlay: { flex: 1, padding: 16, justifyContent: "flex-end", gap: 6 },

  badge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(34,197,94,0.20)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  badgeText: { color: "#B7F7D0", fontSize: 11, fontWeight: "900" },

  title: { color: TEXT, fontSize: 26, fontWeight: "900", marginTop: 2 },
  subtitle: { color: MUTED, fontSize: 12, fontWeight: "600" },

  heart: {
    position: "absolute",
    right: 14,
    top: 14,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(0,0,0,0.25)",
    borderWidth: 1,
    borderColor: BORDER,
    alignItems: "center",
    justifyContent: "center",
  },

  statsRow: { flexDirection: "row", gap: 10 },
  statPill: {
    flex: 1,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  statPillAccent: {
    borderColor: "rgba(34,197,94,0.35)",
    backgroundColor: "rgba(34,197,94,0.08)",
  },
  statIcon: { fontSize: 14 },
  statBig: { color: TEXT, fontSize: 18, fontWeight: "900" },
  statSmall: { color: MUTED, fontSize: 10, fontWeight: "800", letterSpacing: 0.6 },

  card: {
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 22,
    padding: 14,
    gap: 10,
  },
  cardHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  cardTitle: { color: TEXT, fontSize: 14, fontWeight: "900" },
  langPill: {
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  langText: { color: MUTED, fontSize: 11, fontWeight: "700" },
  desc: { color: MUTED, fontSize: 12.5, lineHeight: 18.5, fontWeight: "600" },

  readMore: { flexDirection: "row", alignItems: "center", gap: 6 },
  readMoreText: { color: GREEN, fontSize: 12, fontWeight: "900" },
  readMoreArrow: { color: GREEN, fontSize: 18, marginTop: -2, fontWeight: "900" },

  infoRow: { flexDirection: "row", gap: 10 },
  infoChip: {
    flex: 1,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    padding: 12,
    gap: 6,
    position: "relative",
    overflow: "hidden",
  },
  infoTop: { flexDirection: "row", alignItems: "center", gap: 8 },
  infoIcon: { fontSize: 13 },
  infoTitle: { color: MUTED, fontSize: 11, fontWeight: "800" },
  infoValue: { color: TEXT, fontSize: 16, fontWeight: "900", marginTop: 4 },
  infoSub: { color: MUTED, fontSize: 11, fontWeight: "600" },
  infoTag: {
    position: "absolute",
    right: 10,
    top: 10,
    backgroundColor: "rgba(34,197,94,0.16)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  infoTagText: { color: "#B7F7D0", fontSize: 11, fontWeight: "900" },

  lenderCard: {
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 22,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  avatarDot: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.10)",
    borderWidth: 1,
    borderColor: BORDER,
  },
  lenderName: { color: TEXT, fontSize: 13, fontWeight: "900" },
  lenderSub: { color: MUTED, fontSize: 12, fontWeight: "600" },
  chatBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: "rgba(34,197,94,0.12)",
    borderWidth: 1,
    borderColor: "rgba(34,197,94,0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  chatText: { fontSize: 16 },

  bottom: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 18,
    backgroundColor: BG,
    borderTopWidth: 1,
    borderTopColor: BG,
  },
  cta: {
    marginTop: 10,
    backgroundColor: GREEN,
    borderRadius: 999,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 10,
  },
  tag: {
  backgroundColor: "rgba(34,197,94,0.14)",
  borderWidth: 1,
  borderColor: "rgba(34,197,94,0.28)",
  paddingHorizontal: 10,
  paddingVertical: 7,
  borderRadius: 999,
},
tagText: {
  color: "#B7F7D0",
  fontSize: 12,
  fontWeight: "900",
},
tagMuted: {
  backgroundColor: "rgba(255,255,255,0.06)",
  borderWidth: 1,
  borderColor: "rgba(255,255,255,0.10)",
  paddingHorizontal: 10,
  paddingVertical: 7,
  borderRadius: 999,
},
tagTextMuted: {
  color: "rgba(234,242,238,0.75)",
  fontSize: 12,
  fontWeight: "800",
},
  ctaText: { color: "#052B1C", fontSize: 16, fontWeight: "900" },
  ctaArrow: { color: "#052B1C", fontSize: 18, fontWeight: "900" },
});
