import { StyleSheet } from "react-native";
import { colors } from "@/src/theme/colors";

export const sheetStyles = StyleSheet.create({
  backdrop: {
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.55)",
  },
  wrapper: {
    flex: 1,
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: colors.surfaceDark,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    paddingHorizontal: 16,
    paddingTop: 14,
    maxHeight: "100%",
    height: "100%",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 10,
  },
  title: { color: colors.text, fontSize: 16, fontWeight: "900" },
  close: { color: colors.muted, fontSize: 18, fontWeight: "900" },
  searchWrap: {
    height: 44,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    gap: 10,
    marginBottom: 12,
  },
  searchIcon: { color: colors.muted },
  searchInput: { flex: 1, color: colors.text, fontSize: 14, fontWeight: "700" },
  item: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.04)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
  },
  itemActive: {
    borderColor: "rgba(34,197,94,0.45)",
    backgroundColor: "rgba(34,197,94,0.10)",
  },
  itemLabel: { color: colors.text, fontSize: 14, fontWeight: "800" },
  itemSub: { color: colors.muted, fontSize: 12, fontWeight: "600" },
  check: { color: colors.primary, fontSize: 16, fontWeight: "900" },
});
